pipeline {
    agent any

    environment {
        AWS_REGION   = "us-east-1"
        ECR_REPO     = "secure-jwt-app-repo"
        ACCOUNT_ID   = "017209821473"
        IMAGE_TAG    = "latest"
        CLUSTER_NAME = "secure-jwt-app-cluster"
        SERVICE_NAME = "secure-jwt-app-svc"
        APP_DIR      = "case-1/app"
        ECR_URL      = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                url: 'https://github.com/Mahesh8120/DevOps_Assignment_MaheshJ.git'
            }
        }

        stage('Validate Docker') {
            steps {
                sh '''
                echo "Checking Docker..."
                docker version || exit 1
                '''
            }
        }

        stage('Install Dependencies') {
            steps {
                dir("${APP_DIR}") {
                    sh '''
                    echo "Installing dependencies..."
                    npm install
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir("${APP_DIR}") {
                    sh '''
                    echo "Building Docker image..."

                    export DOCKER_BUILDKIT=0

                    docker build \
                      --platform linux/amd64 \
                      -t $ECR_REPO:$IMAGE_TAG .
                    '''
                }
            }
        }

        stage('Login to ECR') {
            steps {
                withCredentials([[ 
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-auth'
                ]]) {
                    sh '''
                    echo "Logging into ECR..."

                    aws ecr get-login-password --region $AWS_REGION | \
                    docker login --username AWS --password-stdin $ECR_URL
                    '''
                }
            }
        }

        stage('Tag & Push Image') {
            steps {
                sh '''
                echo "Tagging image..."

                docker tag $ECR_REPO:$IMAGE_TAG \
                $ECR_URL/$ECR_REPO:$IMAGE_TAG

                echo "Pushing image..."

                docker push $ECR_URL/$ECR_REPO:$IMAGE_TAG
                '''
            }
        }

        stage('Deploy to ECS Fargate') {
            steps {
                withCredentials([[ 
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-auth'
                ]]) {
                    sh '''
                    echo "Deploying to ECS Fargate..."

                    aws ecs update-service \
                      --cluster $CLUSTER_NAME \
                      --service $SERVICE_NAME \
                      --force-new-deployment \
                      --region $AWS_REGION
                    '''
                }
            }
        }
    }

    post {
        success {
            echo " Deployment Successful"
        }
        failure {
            echo " Pipeline Failed"
        }
    }
}