pipeline {
    agent any

    environment {
        AWS_REGION   = "us-east-1"
        ECR_REPO     = "secure-jwt-app-repo"
        ACCOUNT_ID   = "017209821473"
        IMAGE_TAG    = "${BUILD_NUMBER}"
        CLUSTER_NAME = "secure-jwt-app-cluster"
        SERVICE_NAME = "secure-jwt-app-cluster-svc"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                url: 'https://github.com/Mahesh8120/DevOps_Assignment_MaheshJ.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('case-1/app') {
                    sh 'npm install'
                }
            }
        }

        

        stage('Build Docker Image') {
            steps {
                dir('case-1/app') {
                    sh 'docker build -t $ECR_REPO:$IMAGE_TAG .'
                }
            }
        }

        stage('Push Image to ECR') {
            steps {
                withCredentials([[ 
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-auth'
                ]]) {
                    sh '''
                    aws ecr get-login-password --region $AWS_REGION | \
                    docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

                    docker tag $ECR_REPO:$IMAGE_TAG \
                    $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

                    docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
                    '''
                }
            }
        }

        stage('Start Image Scan') {
            steps {
                withCredentials([[ 
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-auth'
                ]]) {
                    sh '''
                    aws ecr start-image-scan \
                      --repository-name $ECR_REPO \
                      --image-id imageTag=$IMAGE_TAG \
                      --region $AWS_REGION || true
                    '''
                }
            }
        }

        stage('Wait for Scan Result') {
            steps {
                withCredentials([[ 
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-auth'
                ]]) {
                    sh '''
                    echo "Waiting for scan..."

                    while true; do
                      STATUS=$(aws ecr describe-image-scan-findings \
                        --repository-name $ECR_REPO \
                        --image-id imageTag=$IMAGE_TAG \
                        --region $AWS_REGION \
                        --query 'imageScanStatus.status' \
                        --output text)

                      echo "Status: $STATUS"

                      if [ "$STATUS" = "COMPLETE" ]; then
                        break
                      elif [ "$STATUS" = "FAILED" ]; then
                        exit 1
                      fi

                      sleep 10
                    done

                    aws ecr describe-image-scan-findings \
                      --repository-name $ECR_REPO \
                      --image-id imageTag=$IMAGE_TAG \
                      --region $AWS_REGION > scan.json
                    '''
                }
            }
        }

        stage('Fail on High/Critical Vulnerabilities') {
            steps {
                script {
                    def highCount = sh(
                        script: "cat scan.json | grep -i 'HIGH' | wc -l",
                        returnStdout: true
                    ).trim().toInteger()

                    def criticalCount = sh(
                        script: "cat scan.json | grep -i 'CRITICAL' | wc -l",
                        returnStdout: true
                    ).trim().toInteger()

                    if (highCount > 0 || criticalCount > 0) {
                        error "❌ High/Critical vulnerabilities found!"
                    } else {
                        echo "✅ No high/critical vulnerabilities found."
                    }
                }
            }
        }

        stage('Deploy to ECS Fargate') {
            steps {
                withCredentials([[ 
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-auth'
                ]]) {
                    sh '''
                    aws ecs update-service \
                      --cluster $CLUSTER_NAME \
                      --service $SERVICE_NAME \
                      --force-new-deployment \
                      --region $AWS_REGION
                    '''
                }
            }
        }
    }

    post {
        success {
            echo " Deployment Successful"
        }
        failure {
            echo " Pipeline Failed"
        }
    }
}