pipeline {
    agent any

    environment {
        AWS_REGION   = "us-east-1"
        ECR_REPO     = "secure-jwt-app-repo"
        ACCOUNT_ID   = "017209821473"
        IMAGE_TAG    = "${BUILD_NUMBER}"
        CLUSTER_NAME = "secure-jwt-app-cluster"
        SERVICE_NAME = "secure-jwt-app-cluster-svc"
        APP_DIR      = "case-1/app"
        ECR_URL      = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                url: 'https://github.com/Mahesh8120/DevOps_Assignment_MaheshJ.git'
            }
        }

        stage('Validate Docker') {
            steps {
                sh '''
                echo "Checking Docker..."
                docker version || exit 1
                '''
            }
        }

        stage('Install Dependencies') {
            steps {
                dir("${APP_DIR}") {
                    sh '''
                    echo "Installing dependencies..."
                    npm install
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir("${APP_DIR}") {
                    sh '''
                    echo "Building Docker image..."
                    docker build -t $ECR_REPO:$IMAGE_TAG .
                    '''
                }
            }
        }

        stage('Login to ECR & Push Image') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-auth'
                ]]) {
                    sh '''
                    echo "Logging into ECR..."
                    aws ecr get-login-password --region $AWS_REGION | \
                    docker login --username AWS --password-stdin $ECR_URL

                    echo "Tagging image..."
                    docker tag $ECR_REPO:$IMAGE_TAG $ECR_URL/$ECR_REPO:$IMAGE_TAG

                    echo "Pushing image..."
                    docker push $ECR_URL/$ECR_REPO:$IMAGE_TAG
                    '''
                }
            }
        }

        stage('Start Image Scan') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-auth'
                ]]) {
                    sh '''
                    aws ecr start-image-scan \
                      --repository-name $ECR_REPO \
                      --image-id imageTag=$IMAGE_TAG \
                      --region $AWS_REGION || true
                    '''
                }
            }
        }

        stage('Wait for Scan Result') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-auth'
                ]]) {
                    sh '''
                    echo "Waiting for scan to complete..."

                    while true; do
                      STATUS=$(aws ecr describe-image-scan-findings \
                        --repository-name $ECR_REPO \
                        --image-id imageTag=$IMAGE_TAG \
                        --region $AWS_REGION \
                        --query 'imageScanStatus.status' \
                        --output text)

                      echo "Status: $STATUS"

                      if [ "$STATUS" = "COMPLETE" ]; then
                        break
                      elif [ "$STATUS" = "FAILED" ]; then
                        echo "Scan failed"
                        exit 1
                      fi

                      sleep 10
                    done

                    aws ecr describe-image-scan-findings \
                      --repository-name $ECR_REPO \
                      --image-id imageTag=$IMAGE_TAG \
                      --region $AWS_REGION > scan.json
                    '''
                }
            }
        }

        stage('Security Gate (HIGH/CRITICAL Check)') {
            steps {
                script {
                    def findings = sh(
                        script: """
                        cat scan.json | grep -E 'HIGH|CRITICAL' || true
                        """,
                        returnStdout: true
                    ).trim()

                    if (findings) {
                        error " HIGH or CRITICAL vulnerabilities found!"
                    } else {
                        echo " No HIGH/CRITICAL vulnerabilities found."
                    }
                }
            }
        }

        stage('Deploy to ECS Fargate') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-auth'
                ]]) {
                    sh '''
                    echo "Deploying to ECS..."
                    aws ecs update-service \
                      --cluster $CLUSTER_NAME \
                      --service $SERVICE_NAME \
                      --force-new-deployment \
                      --region $AWS_REGION
                    '''
                }
            }
        }
    }

    post {
        success {
            echo " Deployment Successful"
        }
        failure {
            echo " Pipeline Failed"
        }
    }
}